source "http://rubygems.org"
gem "faker"
gem "awesome_print"
gem "exceptional"
gem "resque-scheduler"
gem "SystemTimer"
gem "crypt"
gem "rack-ssl-enforcer"
gem "awesome_print"
gem "rhosync", :git => "git://github.com/rhomobile/rhosync.git", :branch => "2-1-stable", :require => "rhosync/server"
