source "http://rubygems.org"
gem "faker"
gem "awesome_print"
gem "exceptional"
gem "resque-scheduler"
gem "SystemTimer"
gem "crypt"
gem "rack-ssl-enforcer"
gem "awesome_print"
gem "rspec-core", "2.6.0"
gem "rspec", "2.6.0"
# gem "mongrel"
gem "rhosync", "2.1.7"
