#external URL for model proxy
:crm_path: https://mobileproxy.model.insphereis.net/
:exceptional_api_key: b8788d7b2ae404c9661f40215f5d9258aede9c83

#external URL for dev proxy
# :crm_path: http://75.31.122.27/

# :dev:
#     # :crm_path: http://localhost:5000/
#     :crm_path: http://10.174.40.61:5000/
# 
#     # used by jobs/clean_old_opportunity_data
#     :max_opportunity_age_in_days: 60
#     
# :model:
#     # :crm_path: http://localhost:5000/
#     :crm_path: http://10.174.40.61:5000/
# 
#     # used by jobs/clean_old_opportunity_data
#     :max_opportunity_age_in_days: 60
#     
# :production:
#     # :crm_path: http://localhost:5000/
#     :crm_path: http://10.174.40.61:5000/
# 
#     # used by jobs/clean_old_opportunity_data
#     :max_opportunity_age_in_days: 60