# This Gemfile is for deploying to onsite -- Updating to use rhoconnect rhoconnect 5.4 upgrade 
gem "faker"
gem "awesome_print"
gem "exceptional"
gem "resque-scheduler"
gem "crypt19-rb"
gem "rack-ssl-enforcer"
gem "connection_pool"
gem "rhoconnect"
gem "thin"
gem 'rack-fiber_pool'
gem 'async-rack'

