# This Gemfile is for deploying to onsite -- Updating to use rhoconnect 7/12/2012

gem "faker"
gem "awesome_print"
gem "exceptional"
gem "resque-scheduler"
#gem "SystemTimer"
gem "crypt19"
gem "rack-ssl-enforcer"
# Include mogrel gem for local
#gem "mongrel"
gem "rhoconnect"
gem "sqlite3"
gem "thin"
gem 'rack-fiber_pool'
gem 'async-rack'